### ISSUE TITLE
mmmagic install through proxy

### ISSUE THREAD

**Issue by clydehunt76** [mscdex/mmmagic#100]
We have an artifact repository from which all of our npm install activities are actioned. mmmagic invokes a rebuild and seems to try reaching out to allow a node-gyp rebuild. (to 104.20.23.46:443?) - Can I implement a setting (in .npmrc) that points the node-gyp rebuild requirement at a proxy? - or bypasses that stage completely?

**Comment by mscdex** [comment]
104.20.23.46 is nodejs.org, which is where node-gyp fetches headers (only happens once per node version) for compiling addons.

npm already supports http/https proxies. For example, you could set the proxy information in your global npm config via:

```
$ npm config set proxy http://proxy.company.com:8080
$ npm config set https-proxy http://proxy.company.com:8080
```

You can also use environment variables or command line flags.

If you have further issues/questions about this particular matter, you are better off asking on [npm's issue tracker](https://github.com/npm/npm/issues) as this is not specific to this addon.
