### ISSUE TITLE
Update libmagic version to 5.31 due to bugs in 5.28 - Some xls and ppt files are identified as application/CDFV2-unknown 

### ISSUE THREAD

**Issue by RavivIsraeli** [mscdex/mmmagic#107]
https://bugs.gw.com/view.php?id=559

**Comment by mscdex** [comment]
Please try the master branch, I have merged in libmagic 5.32 now.

**Comment by Alessy** [comment]
It's working. When will be  published in npm repository?

**Comment by mscdex** [comment]
@Alessy Pretty soon, I wanted to give a chance to those who were having various issues with the previous release to test the master branch first.

**Comment by sovietspaceship** [comment]
Same issue. Current npm release is outdated, using this in production but doc files are not being recognised - considering switching to another library unless this is fixed soon. Can you please release a new version with the latest changes?

**Comment by mscdex** [comment]
I've published v0.4.6.
