### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by Chatosh** [mscdex/mmmagic#110]
When I try to run sample code, it throws me error as "Cannot find module '../build/Release/magic' ".

**Comment by mscdex** [comment]
It sounds like the addon did not get compiled. If you installed with `npm install mmmagic`, post the console output. My guess is python 2.7 is not installed and/or the compiler toolchain is not installed (e.g. gcc/clang on *nix, VC or Build Tools on Windows).

**Comment by mterczynski** [comment]
I got the same issue. Console output:
![image](https://user-images.githubusercontent.com/27309340/28995614-bd1520da-79ed-11e7-9b25-080b4d15a79b.png)

**Comment by mscdex** [comment]
@mterczynski You're missing Python. See the general build requirements for all node addons [here](https://github.com/nodejs/node-gyp#on-windows).

**Comment by mterczynski** [comment]
This worked for me:
https://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm
