### ISSUE TITLE
svg started with BOM detected as xml

### ISSUE THREAD

**Issue by rewle** [mscdex/mmmagic#113]
Hello

If .svg file starts with BOM(EF BB BF), mmmagic detected this as 'xml'.

In attachment test1.svg and test2.svg is equal, but mmmagic return different type

[test.zip](https://github.com/mscdex/mmmagic/files/1197049/test.zip)

**Comment by mscdex** [comment]
Please try the master branch, I have merged in libmagic 5.32 now.

**Comment by mscdex** [comment]
I've published v0.4.6. If this is still a problem, please report the issue upstream to the libmagic/file bug tracker.
