### ISSUE TITLE
regex error 11 for `	\*|([0-9]+[MIDNSHPX=])+)

### ISSUE THREAD

**Issue by FranckDepoortere** [mscdex/mmmagic#114]
Hello,

We use mmmagic 4.5 to detect types of content in uploaded files on our WebSite.
Most of the time,  it's Text File with Tab Delimited that our customers upload.

But sometime, our customers have the following error :

regex error 11 for `	\*|([0-9]+[MIDNSHPX=])+)	', (unbalanced () at offset 24    )    at Error (native) 

We have this error with the attached file "NOOK.txt" and this code:
[NOOK.txt](https://github.com/mscdex/mmmagic/files/1200619/NOOK.txt)

> import * as mmm from 'mmmagic';
> var magic = new mmm.Magic(mmm.MAGIC_MIME_TYPE);
> magic.detectFile(filename, function(err, result) {
>       if (err) throw err;
> 	return result;
>   });
> 

The problem is caused by the TAB between "046" and "MY ADDRESS", line 0 of the file, column 29:  
[NOOK.txt](https://github.com/mscdex/mmmagic/files/1200619/NOOK.txt)
If you replace this Tab by an other character, there is no error.

Thanks for your help.
Franck

**Comment by FranckDepoortere** [comment]
Ok, the bug is in MagicLib 5.28: 
Solution: fix the regEx in MagicLib and recompile (a parenthesis is missing on a regEx, file magic\Magdir\bioinformatics, line 165
>>>>>0		regex	=\t(\\*|([0-9]+[MIDNSHPX=])+)\t
but the best solution would be to upgrade mmmagic dependencies and include MagicLib 5.31

We're looking forward to having a new version of mmmagic the year :)
Franck

**Comment by mscdex** [comment]
Please try the master branch, I have merged in libmagic 5.32 now.
