### ISSUE TITLE
non ASCII char in test/fixtures/tést.txt

### ISSUE THREAD

**Issue by max-bondarenko** [mscdex/mmmagic#117]
subj file fails npm install with node module build on lightwait docker image.

test/fixtures/tést.txt resolves to test/fixtures/t??st.txt file and gradle can`t store it in its cache.

can U rename it to just test.txt (plain ASCII name )

```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of output files for task 'npmInstallV2' property '$1' during up-to-date check.
> Failed to create MD5 hash for file '/home/jenkins/workspace/AWYJS4QAHQ/frontend/v1/node_modules/mmmagic/test/fixtures/t??st.txt'.
```

**Comment by mscdex** [comment]
Duplicate of https://github.com/mscdex/mmmagic/issues/67.
