### ISSUE TITLE
can't install due to permission denied error

### ISSUE THREAD

**Issue by wxl** [mscdex/mmmagic#120]
I'm actually trying to install [apaste][1] on Ubuntu Zesty but I keep getting hung up on mmmagic. What leads me here is the fact that I can't even explicitly install mmmagic on its own and that the error I get is the same:

```
$ sudo npm install -g mmmagic

> mmmagic@0.4.5 install /usr/local/lib/node_modules/mmmagic
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/mmmagic/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 4.10.0-38-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/mmmagic
gyp ERR! node -v v6.12.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mmmagic@0.4.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmmagic@0.4.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Now this is baffling. Why should `sudo` have problems writing to nearly any directory? Permissions are 755. When I originally looked, instead of being owned by root:root, all of node_modules was owned by nobody:my_user. I've done `chown -R` with root:root and it's not any better. I've also made sure it was nobody:my_user and tried with and without `sudo`. Nope. Most importantly, I have no problem installing other node modules.

[1]: https://www.npmjs.com/package/apaste

**Comment by mscdex** [comment]
I don't know, this addon is not doing anything permissions-wise or anything special during installation.

**Comment by wxl** [comment]
I tried to reproduce this on a fresh zesty system and couldn't. I don't
know what is the problem but something has messed it up. If, by chance,
you get any great ideas, I'd love to hear them. Meanwhile, if it's not
reproducible, you can't fix it, so you might as well close it. 😩
