### ISSUE TITLE
wrong detect result about excel mime type 

### ISSUE THREAD

**Issue by sabakugaara** [mscdex/mmmagic#121]
detect `xx.xlsx` file got `application/zip` mimetype.

- os: mac
- version: 0.4.6

test code:
```
 var mmm = require('mmmagic'),
      Magic = mmm.Magic;

var magic = new Magic(mmm.MAGIC_MIME_TYPE);
magic.detectFile('xxx.xlsx', function(err, result) {
    if (err) throw err;
    console.log(result);
});
```

**Comment by mscdex** [comment]
File type detection issues should be submitted upstream to the libmagic/file bug tracker. However, in this particular case, I don't know if libmagic would be willing to open a zip file to attempt further detection (since xlsx files are zip files).

**Comment by sabakugaara** [comment]
Thank you for the repley @mscdex
