### ISSUE TITLE
Error: line 61: regex error 14 for `^[[:space:]]*class[[:space:]]+[[:digit:][:alpha:]:_]+[[:space:]]*\{(.*[ ]*)*\}(;)?$', (failed to get memory)

### ISSUE THREAD

**Issue by seally1186** [mscdex/mmmagic#124]
Running this script

```js
const mmmagic = require("mmmagic");
const M = new mmmagic.Magic();
M.detectFile("foo.js", (err, res) => {
  console.log(err);
  console.log(res);
  process.exit(0);
});
```

on this file

```js
class foo { }
test = new abcde();
```

results in the error

```
Error: line 61: regex error 14 for `^[[:space:]]*class[[:space:]]+[[:digit:][:alpha:]:_]+[[:space:]]*\{(.*[
]*)*\}(;)?$', (failed to get memory)
```

I can't tell what's causing this, but it seems sensitive to the length of the strings. For example, if `test` is `bar`, it doesn't have an issue.

No issues running `file` (5.32) on the above file. Tested with mmmagic 0.4.6, node 8.9.4, gcc 5.4.0.

**Comment by mscdex** [comment]
Can you try the master branch (`npm install https://github.com/mscdex/tarball/master`)? I think this should be fixed now.

**Comment by seally1186** [comment]
Seems to be working great. Thanks for the quick fix!

**Comment by mscdex** [comment]
Thanks for the confirmation!
