### ISSUE TITLE
Sefgault in NODE 8.9.1 & 8.6.0

### ISSUE THREAD

**Issue by corybill** [mscdex/mmmagic#125]
I wanted to see if anyone had reported Segfault issues in later version of Node 8? I'll add more information to this ticket as I acquire it, but below is the information I have gathered so far.

PID 22 received SIGSEGV for address: 0x7ff80b411a0f
/srv/package/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x1a9b)[0x7ff82d379a9b]
/lib64/libpthread.so.0(+0xf130)[0x7ff831387130]
/srv/node_modules/mmmagic/build/Release/magic.node(+0x14557)[0x7ff82ed41557]
/srv/node_modules/mmmagic/build/Release/magic.node(+0x16078)[0x7ff82ed43078]
/srv/node_modules/mmmagic/build/Release/magic.node(magic_buffer+0x3f)[0x7ff82ed3a69f]
/srv/package/node_modules/mmmagic/build/Release/magic.node(_ZN5Magic10DetectWorkEP9uv_work_s+0x5d)[0x7ff82ed385dd]
node[0x1455521]
/lib64/libpthread.so.0(+0x7df3)[0x7ff83137fdf3]
/lib64/libc.so.6(clone+0x6d)[0x7ff8310ad3dd]
./bootstrap.sh: line 11:    22 Aborted                 (core dumped) node ${ARGS} --stack-size=65500 --max-old-space-size=3072 lib/app.js

**Comment by mscdex** [comment]
Are you using the latest version (0.5.0 as of this writing)?

Did you try re-building the addon if you upgraded to a new major version of node?

**Comment by corybill** [comment]
Closing. Code wrapped the buffer inside of another Buffer. If that wasn't bad enough, it was using "new Buffer" syntax (which has its own issues) instead of the Buffer factory function.
