### ISSUE TITLE
Node Gyp silently failing?

### ISSUE THREAD

**Issue by jamespedid** [mscdex/mmmagic#126]
When I do an npm install the output looks like: 

![image](https://user-images.githubusercontent.com/1280555/39896020-8de8f8d2-547a-11e8-9998-026ce6cb7597.png)

When I require('mmmagic') in a node file, I get

![image](https://user-images.githubusercontent.com/1280555/39896004-7d4fcdac-547a-11e8-98a3-69c11ac99b5b.png)

Any clue as to why this might be happening is appreciated. Using Linux Mint 18.3

**Comment by mscdex** [comment]
Is that really all that was shown during `node-gyp rebuild`? Does the file actually exist ('mmmagic/build/Release/magic.node')?

**Comment by jamespedid** [comment]
This is what the directory structure in the node modules folder is after doing an npm install:

![image](https://user-images.githubusercontent.com/1280555/39927935-d9bdc864-5501-11e8-8851-be83b2691bd5.png)

If I go to the node_modules directory from the command line and do node_gyp build, then the file is building. However, when I try and run it I get the following error:

![image](https://user-images.githubusercontent.com/1280555/39927994-10e751d4-5502-11e8-94c7-325e8ce513a2.png)

![image](https://user-images.githubusercontent.com/1280555/39928020-2b47007e-5502-11e8-9104-f74486d07898.png)

I'm sure the error is local to my build machine, but if you have any ideas please let me know.

**Comment by mscdex** [comment]
This new error is fairly clear: the addon was built with an older (major) version of node but you're trying to use it with a newer (major) version of node. When you're doing this explicitly, make sure to either do `node-gyp rebuild` or `node-gyp configure` followed by `node-gyp build`.

**Comment by jamespedid** [comment]
Ok I was able to get the issue fixed. thanks!
