### ISSUE TITLE
Node 10.9 NaN Issue

### ISSUE THREAD

**Issue by cbratschi** [mscdex/mmmagic#130]
This module is not compatible with Node 10.x:

error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..\src\binding.cc)

Upgrading to NaN 2.10 will solve the issue.

**Comment by mscdex** [comment]
This should be fixed in 99a44f2560de542d02bea1b916112849e4ab6858. Thanks for the heads up!
