### ISSUE TITLE
Executable detected as `text/plain`

### ISSUE THREAD

**Issue by george-norris-salesforce** [mscdex/mmmagic#138]
Is there anyway to detect if file is an executable? Technically it is a text file, but would be nice to be able to filter these types of files. Currently a `my-script.command` with added executable privileges is being detected as `text/plain`.

**Comment by mscdex** [comment]
`mmmagic` focuses on analyzing content for detecting content type information. If you want to know any more than what `file` can provide then you will have to use some other means to obtain that information.

For example, if you want to check if a file has the executable permission you can easily use node core for that (`fs.stat()` and checking `stats.mode`).
