### ISSUE TITLE
Build fails with node ^12.0.0

### ISSUE THREAD

**Issue by tiger31** [mscdex/mmmagic#139]

**Comment by mscdex** [comment]
Fixed in 78decce5ff93db8f713a5bb0041ce31ef705a1b9.

**Comment by codingride** [comment]
One more question regarding this issue if I may.
When I clone or download the latest repo from github it compiles without any issues.
But when I include it in my project dependencies and install it, it gives me "failed with exit code: 1" error.
So I was wondering if the latest repo was pushed or updated on npm servers?

**Comment by mscdex** [comment]
There isn't a published version on npm yet, if that's what you're asking.

**Comment by codingride** [comment]
Thank you for your answer.
Is it going to be published on npm soon, if I can ask?
