### ISSUE TITLE
Error: "Failed at the mmmagic@0.5.0 install script."

### ISSUE THREAD

**Issue by Wavey-web** [mscdex/mmmagic#144]
So I am having trouble installing the package from `npm install --only=production` and it ended up in this kind of error:
Link to the error log since its very long:
https://transfer.sh/1332zO/hiel1.txt

**Comment by mscdex** [comment]
The npm error log file does not include node-gyp output unfortunately, so it's not useful when debugging node addon installation issues. The actual build errors should be displayed in the console/terminal though.

**Comment by Wavey-web** [comment]
So how can i fix it?

**Comment by mscdex** [comment]
Depends on the output from node-gyp that is only printed to the console/terminal.

**Comment by Wavey-web** [comment]
still didn't work.
`npm ERR! mmmagic@0.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmmagic@0.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by mscdex** [comment]
Before going any further, try using the latest version of `mmmagic` as some build issues were fixed since v0.5.0.

**Comment by Wavey-web** [comment]
ah so I guess someone uses the outdated one.

**Comment by Wavey-web** [comment]
imma try it

**Comment by Wavey-web** [comment]
wait how can I update the package?

**Comment by mscdex** [comment]
If it's not a direct dependency (e.g. you're using `mmmagic` explicitly in your own code), you'll have to submit a PR/issue to whichever project is using it to have them update the version/version range.

**Comment by Wavey-web** [comment]
ah ok

**Comment by Wavey-web** [comment]
Imma close this since I solved it
The reason is that I forgot to do `sudo` at the beginning of an command.
