### ISSUE TITLE
Facing 404 error while installing mmagic package

### ISSUE THREAD

**Issue by RajatBhardwaj007** [mscdex/mmmagic#172]
I am facing 404 error as shown below, while installing mmagic package. I am using node version v18.16.0. I tried with node version v12.22.0 but same result.

`rajatbhardwaj@Sanchays-MacBook-Pro tmp % npm i mmagic
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/mmagic - Not found
npm ERR! 404 
npm ERR! 404  'mmagic@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rajatbhardwaj/.npm/_logs/2024-04-17T03_18_24_107Z-debug-0.log`

**Comment by mscdex** [comment]
You misspelled the package name.
