### ISSUE TITLE
Error on Azure Deployment

### ISSUE THREAD

**Issue by mamarildon** [mscdex/mmmagic#28]
remote: npm ERR! Failed at the mmmagic@0.3.8 install script.
remote: npm ERR! This is most likely a problem with the mmmagic package,
remote: npm ERR! not with npm itself.
remote: npm ERR! Tell the author that this fails on your system:
remote: npm ERR!     node-gyp rebuild
remote: npm ERR! You can get their info via:
remote: npm ERR!     npm owner ls mmmagic
remote: npm ERR! There is likely additional logging output above.
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "d:\\Program Files (x86)\\nodejs\\0.10.29\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.10\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd d:\home\site\wwwroot
remote: npm ERR! node -v v0.10.29
remote: npm ERR! npm -v 1.4.10
remote: npm ERR! code ELIFECYCLE
remote: npm
remote: 
remote: Error - Changes committed to remote repository but deployment to website failed.

**Comment by midhun1993** [comment]
@dmamaril  Hello,
  I'm experiencing the same issue, How we can fix it ?
