### ISSUE TITLE
Is there a sync version encapsulating libmagic in node.js ?

### ISSUE THREAD

**Issue by YorkTsai2012** [mscdex/mmmagic#32]
Undoubtedly, this module based on libmagic is so fantastic.
What is a little pity that the mmmagic is async.
Actually, in node.js,  many file manipulation APIs have both sync and async versions.
If the mmmagic also has a sync version, it will be more appreciated.
@mscdex

**Comment by ChALkeR** [comment]
Won't https://github.com/abbr/deasync help?

**Comment by YorkTsai2012** [comment]
@ChALkeR Thanks a lot  ^-^

**Comment by mscdex** [comment]
There is no plan for synchronous counterparts for now.
