### ISSUE TITLE
Get exactly file type for text content

### ISSUE THREAD

**Issue by djibythiaw** [mscdex/mmmagic#37]
Hi,
With that module can we get the axactly content-type for a file containing text. Actually for a file containing text I just have the mime content-type: "text/plain". Can I have something like "text/csv" if the content is csv or "application/json" if the content is csv.
Thanks

**Comment by mscdex** [comment]
It's not quite that simple. libmagic typically does not do that kind of inspection of text files. You could check the file extension instead to check for `text/csv` or `application/json` if you need those specific mime types (this is what Apache does IIRC).

**Comment by djibythiaw** [comment]
Ok I see thank you
