### ISSUE TITLE
Not detecting mime type audio/mpeg when file has embedded art.

### ISSUE THREAD

**Issue by carsy** [mscdex/mmmagic#40]
The  resulting type is application/octet-stream
example: https://kubbi.bandcamp.com/album/something-new

**Comment by mscdex** [comment]
What version of `mmmagic` are you using?

**Comment by carsy** [comment]
mmmagic@0.3.13

**Comment by mscdex** [comment]
`mmmagic` just uses the magic file from the upstream libmagic. If there are misdetected files, you should file an issue on their bug tracker [here](http://bugs.gw.com/my_view_page.php). There have been a couple of issues with this format before in the past, so it's possible they're still missing some edge cases.

**Comment by carsy** [comment]
Thanks. That is indeed the case. I was able to reproduce the problem:

```bash
$ file --mime test.mp3     # no embedded art
test.mp3: audio/mpeg; charset=binary
$ file --mime test2.mp3   # has embedded art
test2.mp3: application/octet-stream; charset=binary
```

I'll be reporting the bug there then ;)

**Comment by mscdex** [comment]
Closing this now as I get `audio/mpeg` in the master branch for the linked mp3.

**Comment by carsy** [comment]
Yes! Sorry I didn't update this.
