### ISSUE TITLE
Possibility to specifiy multiple magic files

### ISSUE THREAD

**Issue by nknapp** [mscdex/mmmagic#43]
I'd like to have the possibility to specify multiple magic-files instead of just a custom one, or is this already possible?
My use case is to detect files using default magic-files, but in addition a few file-types that can't be detected by the default file.

**Comment by mscdex** [comment]
I believe this should be possible already. libmagic actually parses the magic file filename as a path separated list of filenames. So on *nix they'd be separated by `:` or `;` on Windows. Example: `'/etc/magic.mgc:/home/foo/.magic.mgc'`

**Comment by nknapp** [comment]
You're right, it works, thanks. I just noticed my mistake: When reading the man-page of "file", I read "comma-separated list" instead of "colon-separated list". So I tried `/etc/magic.mgc,/home/foo/.magic.mgc`  which did not work.
