### ISSUE TITLE
Build fails on Solaris variants (like SmartOS) due to missing sig_t

### ISSUE THREAD

**Issue by alyssackwan** [mscdex/mmmagic#44]
The libmagic source uses sig_t in compress.c where it bombs when building on SmartOS.

Please see https://github.com/FreeRADIUS/freeradius-server/issues/765.

**Comment by mscdex** [comment]
IMHO this is something that should be fixed [upstream](http://bugs.gw.com/) in libmagic. I'm hesitant to start floating patches, let alone for a platform I'm not familiar with and would have a hard time maintaining external support for.

**Comment by mscdex** [comment]
5.23 is in master, which may fix the sig_t issue. Please give it a try and let me know if it solves things for you.
