### ISSUE TITLE
webp detected as application/octet-stream

### ISSUE THREAD

**Issue by michaelsanford** [mscdex/mmmagic#45]
My use-case is detecting file types being uploaded to a server originating from a custom native client with a custom network stack. So far, MIME type detection has been flawless.

However, I noticed that webp image files are detected as `application/octet-stream` rather than as [the expected](http://en.wikipedia.org/wiki/WebP) `image/webp`. Here is [one of the test images](https://dl.dropboxusercontent.com/u/529693/1.webp).

Thanks for a great module.

**Comment by mscdex** [comment]
I know there was support for `image/webp` at one time, so maybe there's a regression somewhere. You might file a bug about it on [libmagic's bug tracker](http://bugs.gw.com/). The bundled magic file in mmmagic comes directly from upstream.

**Comment by michaelsanford** [comment]
It seems it was already bugged and resolved: http://bugs.gw.com/view.php?id=427

I'll just have to wait for the `libmagic` patch to trickle down to my distro (or compile from source — but I don't really feel like that right now).

Thanks, @mscdex !

**Comment by mscdex** [comment]
Ah ok I missed that somehow. Hopefully they will release 5.23 soon so I can incorporate it.

**Comment by michaelsanford** [comment]
Great! :+1: Looking forward to it.

**Comment by mscdex** [comment]
Ok, 5.23 is in master. Please give it a try and let me know if it solves things for you.
