### ISSUE TITLE
2 Warnings during npm install 

### ISSUE THREAD

**Issue by danielflippance** [mscdex/mmmagic#46]
FYI - I installed mmmagic as part of node-pluploader and I noticed the following two warnings during the rebuild which was executed when calling npm install node-pluploader:

    > mmmagic@0.3.13 install /blah/blah/node_modules/node-pluploader/node_modules/mmmagic
    > node-gyp rebuild

    CC(target) Release/obj.target/libmagic/deps/libmagic/src/apprentice.o
    CC(target) Release/obj.target/libmagic/deps/libmagic/src/apptype.o
    CC(target) Release/obj.target/libmagic/deps/libmagic/src/ascmagic.o   
    CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf.o
    ../deps/libmagic/src/cdf.c:303:6: warning: implicit declaration of function 'pread' is invalid in C99 [-Wimplicit-function-declaration]
        if (pread(info->i_fd, buf, len, off) != (ssize_t)len)
            ^
    ../deps/libmagic/src/cdf.c:1048:4: warning: expression result unused [-Wunused-value]
                        CDF_TOLE2(ce[i].ce_name[k]);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../deps/libmagic/src/cdf.c:75:23: note: expanded from macro 'CDF_TOLE2'
    #define CDF_TOLE2(x)    ((uint16_t)(NEED_SWAP ? _cdf_tole2(x) : (uint16_t)(x)))
                         ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf_time.o
    CC(target) Release/obj.target/libmagic/deps/libmagic/src/compress.o
    ...

**Comment by mscdex** [comment]
These come from libmagic itself, not this binding, and can be ignored.
