### ISSUE TITLE
Error: /app/node_modules/mmmagic/build/Release/magic.node: invalid ELF header \\ Running on Ubuntu 14.04

### ISSUE THREAD

**Issue by Ryanmtate** [mscdex/mmmagic#50]
when I run npm install, the build is successful; however when I start the application, the applications fails with invalid ELF header. Unsure why.. any help is much appreciated. 

Node version 0.12.2

-------
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: /app/node_modules/mmmagic/build/Release/magic.node: invalid ELF header
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/app/node_modules/mmmagic/index.js:3:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by mscdex** [comment]
Did you copy the `node_modules` directory from another system where `mmmagic` was originally installed/built? That's typically when the error occurs, when you try to use a compiled addon from another system with a different CPU architecture (e.g. x86 vs x86-64) or platform (Windows vs *nix) for example.

**Comment by Ryanmtate** [comment]
@mscdex Thanks for the message. I am running an application in a docker container using a Dockerfile and .dockerignore file, in which the node_modules folder is ignored during the initial build context, and later added via a fresh npm install in the docker container, which is based on Ubuntu 14.04 image. Originally the build was compiled on an OS X machine. 

However, I have tried npm cache clean, npm rm -rf node_modules npm install while inside the docker container; Yet, the error persists.

Still troubleshooting-- feel free to shoot out any suggestions if you think of any. Thanks, Ryan

**Comment by mscdex** [comment]
I'm a bit confused, are you building the addon (via `npm install mmmagic`) inside the Ubuntu 14.04 image?

You could try manually downloading a tarball (e.g. `curl -L https://github.com/mscdex/mmmagic/tarball/master | tar zx`), then using `node-gyp rebuild` (you may need to `npm install -g node-gyp` first to make the command available) inside the root of the extracted tarball directory to manually build it. Then make a simple test script (or one of the examples from the readme) to verify that the addon is working properly.

If that still doesn't work, I have no idea, as I'm not familiar enough with Docker to make more suggestions.

**Comment by Ryanmtate** [comment]
@mscdex Thanks for your help. I figured this was more an issue related to how I was building the dockerfile than mmmagic itself, which it turned out to be. Closing this.

**Comment by jspizziri** [comment]
@Ryanmtate 

What exactly did you do to resolve your issue. I'm building a Dockerfile and my project has mmmagic installed as a dependency as well and I'm getting the same issue.

Thanks!

**Comment by jspizziri** [comment]
nvm,

I needed to ignore my `node_modules` as suggested above. I'm new to docker so I wasn't familiar with the `.dockerignore`.
