### ISSUE TITLE
mmmagic is not detecting this jpeg

### ISSUE THREAD

**Issue by 4poc** [mscdex/mmmagic#54]
Not sure what exactly is going on here, but I've got a JPEG file that isn't detected as such. Maybe someone can figure it out?

* [foo.jpeg](https://cloud.githubusercontent.com/assets/168797/8216110/c83b4126-1534-11e5-838d-21f3dba13638.jpeg)
* [bar.jpeg](https://cloud.githubusercontent.com/assets/168797/8216111/c83c2384-1534-11e5-88a3-8317a905556f.jpeg)

```
% npm list
/home/apoc/mmmagic-bug
└─┬ mmmagic@0.3.14
  └── nan@1.8.4

% file *.jpeg
bar.jpeg: JPEG image data, JFIF standard 1.01
foo.jpeg: JPEG image data, JFIF standard 1.01
% identify foo.jpeg
foo.jpeg JPEG 1009x1427 1009x1427+0+0 8-bit sRGB 298KB 0.000u 0:00.000
% identify bar.jpeg
bar.jpeg JPEG 762x1100 762x1100+0+0 8-bit sRGB 209KB 0.000u 0:00.000

% cat bug.js
var mmm = require('mmmagic');
var Magic = mmm.Magic;

function detect (filename) {
    var magic = new Magic(mmm.MAGIC_MIME_TYPE);
    magic.detectFile(filename, function (err, result) {
        if (err) {
            console.log('ERROR');
            console.log(err);
        }
        else {
            console.log('%s: %s', filename, result);
        }
    });
}

detect('foo.jpeg');
detect('bar.jpeg');

% node bug.js
foo.jpeg: image/jpeg
bar.jpeg: application/octet-stream

```

**Comment by mscdex** [comment]
It works for me on master (where libmagic 5.23 is merged). Can you try with it as well?

**Comment by MalyshevDmitry** [comment]
I have the same problem.
mmmagic@0.3.14

**Comment by mscdex** [comment]
@MalyshevDmitry Can you try with the master branch and let me know if that helps or not?

**Comment by MalyshevDmitry** [comment]
@mscdex It helped. Thank you!

**Comment by raghavgarg1257** [comment]
Hey, I am having the same problem, `mmmagic` is detecting a `jpeg` image as 

     application/octet-stream

Can you please guide me how to use v5.23. I have installed using `npm install mmmagic --save` and it installed the v0.4.5.
