### ISSUE TITLE
Hi. There seems to be an issue when installing this package when using vs2014

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [mscdex/mmmagic#57]
![](http://i.imgur.com/VVTrv34.png)

I suppose this might be the solution 

http://stackoverflow.com/questions/27754492/vs-2015-compiling-cocos2d-x-3-3-error-fatal-error-c1189-error-macro-definiti

![](http://i.imgur.com/mVXut6n.png)

**Comment by mscdex** [comment]
What version are you installing? mmmagic v0.4.0 should already have the fix for this. I just double checked with VS2015 again and it compiles fine.

**Comment by DominikDitoIvosevic** [comment]
Ill check the version they are depending on when I get home. It is very
possible that they have targeted an older version

**Comment by DominikDitoIvosevic** [comment]
My sincere apologies. They were depending on an older 0.3.16 version as is showed in the screenshot. mmmagic works as it should with the newer version
