### ISSUE TITLE
Can't Make, Node 4.1.0, CentOS 6.7 x64

### ISSUE THREAD

**Issue by rhettl** [mscdex/mmmagic#59]
Hello as stated, I have a 64bit server running CentOS 6.7. I tried this yesterday with Node 0.10.x and 4.0.0 and today with Node 4.1.0. I have created a [Gist](https://gist.github.com/rhettl/73ebce88bc1ddc4415c3) with the `npm install` command, `npm install --verbose` command, and `package.json` it is pointing to.

I also tried this on my Raspberry Pi 1B, ARMv61, Raspbian, Node 4.0.0, with the same error.

Thanks a lot,
-- Rhett

**Comment by mscdex** [comment]
These errors indicate that your compiler is too old. It should have worked on v0.10, but io.js v1.0 and newer (including node v4.x) [require gcc/g++ 4.8 or newer or clang/clang++ 3.4 or newer](https://github.com/nodejs/node#build).

**Comment by rhettl** [comment]
Ahhh, thank you very much. I have gcc-g++ 4.4.7 which yum thinks is my latest. I am `make; make install`-ing gcc-g++ now. I haven't looked at clang yet, but I am sure you are right there too.

**Comment by mscdex** [comment]
FWIW I've installed gcc/g++ 4.8+ on CentOS 5 and 6 before using a recent version of devtoolset (2 or newer).

**Comment by rhettl** [comment]
`Clang@3.4` and `Gcc-g++@4.8.2`  installed and `npm install` succeeded Thanks!
