### ISSUE TITLE
Runtime error with newer node versions

### ISSUE THREAD

**Issue by strarsis** [mscdex/mmmagic#61]
Using sample code from mmmagic documentation:
````
 var mmm = require('mmmagic'),
      Magic = mmm.Magic;

  var magic = new Magic(mmm.MAGIC_MIME_TYPE | mmm.MAGIC_MIME_ENCODING);
  // the above flags can also be shortened down to just: mmm.MAGIC_MIME
  magic.detectFile('node_modules/mmmagic/build/Release/magic.node', function(err, result) {
      if (err) throw err;
      console.log(result);
      // output on Windows with 32-bit node:
      //    application/x-dosexec; charset=binary
  });
````

Error when running the code:
````
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: [...]/node_modules/mmmagic/build/Release/magic.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> ([...]/node_modules/mmmagic/lib/index.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
````

Affected node versions (which I tried): v4.0.0, v0.12.4

With best regards

**Comment by mscdex** [comment]
Ok, so either you need to rebuild the addon after upgrading node, or somehow an older version of node is being used to run your script.

The former you can typically fix with an `npm rebuild` from where you did `npm install mmmagic`. The latter can be fixed by double checking `node -v`.

**Comment by strarsis** [comment]
node -v:
````
v4.0.0
````
Double-checked the paths also.

I did a full rebuild, by removing the folder in node_modules and/or running npm rebuild but the issue persists.

**Comment by mscdex** [comment]
What do `npm -v` and `npm ls mmmagic` show?

How did you install/upgrade node?

**Comment by strarsis** [comment]
Did a npm self-upgrade before:
$ npm -v
````
3.3.3
````

````
$ npm ls mmmagic
/home/user/mime-test
└── mmmagic@0.4.0
````

Installed node using last nvm.

**Comment by mscdex** [comment]
nvm may have issues compiling addons properly. Try `npm install node-gyp -g` and then `node-gyp rebuild` in the root directory for `mmmagic` and then try the sample code again.

**Comment by strarsis** [comment]
It works now with node v5.3.0.
