### ISSUE TITLE
Small buffer incorrectly identified as application/zlib

### ISSUE THREAD

**Issue by ScopiCisco** [mscdex/mmmagic#62]
The following code should report text/plain.

var mmm = require('mmmagic');
var magic = new mmm.Magic(mmm.MAGIC_MIME_TYPE);
var buf = new Buffer('80AD0114343054825D');
magic.detect(buf, function(err, type) {
   console.log(type);
});

magic.detectFile('./smallFile', function(err, type) {
   console.log(type);
});

This program reports 

application/zlib as the type.

when the file "smallFile" has the exact same text, still get the application/zlib.  

From Linux and Mac if I run "file smallFile" I properly get text/plain

I copied /usr/share/file/magic.mgc over the shipped magic.mgc (as a test) and I get back undefined.

Any thoughts?

**Comment by mscdex** [comment]
I tested with master and I get `text/plain`. It must have gotten fixed in libmagic 5.25. A new version has been published.

**Comment by ScopiCisco** [comment]
Many thanks Brian for the quick response and publishing a new version.
