### ISSUE TITLE
Error npm install mmmagic

### ISSUE THREAD

**Issue by suver** [mscdex/mmmagic#63]
^
../node_modules/nan/nan.h: In function ‘void Nan::LowMemoryNotification()’:
../node_modules/nan/nan.h:485:32: error: ‘class v8::Isolate’ has no member named ‘LowMemoryNotification’
     v8::Isolate::GetCurrent()->LowMemoryNotification();
                                ^
../node_modules/nan/nan.h: In function ‘void Nan::ContextDisposedNotification()’:
../node_modules/nan/nan.h:489:32: error: ‘class v8::Isolate’ has no member named ‘ContextDisposedNotification’
     v8::Isolate::GetCurrent()->ContextDisposedNotification();
                                ^
make: *** [Release/obj.target/magic/src/binding.o] Ошибка 1
make: Выход из каталога `/mnt/Projects/projects/farpse/NJSCore/node_modules/mmmagic/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Linux 3.13.0-66-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/Projects/projects/farpse/NJSCore/node_modules/mmmagic
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

npm ERR! Linux 3.13.0-66-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mmmagic"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! mmmagic@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mmmagic@0.4.1 install script.
npm ERR! This is most likely a problem with the mmmagic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mmmagic
npm ERR! There is likely additional logging output above.

**Comment by mscdex** [comment]
You need to upgrade to a stable version of node. node v0.11.x was an unstable branch (v0.12.x was the next stable branch after v0.10.x).

FWIW though, node v4.2.1 is the latest stable version as of this writing.

**Comment by suver** [comment]
thk, it`s good advice

**Comment by gokceyucel** [comment]
290 error Linux 2.6.32-279.el6.x86_64
291 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production" "--verbose"
292 error node v4.2.1
293 error npm  v2.14.7
294 error code ELIFECYCLE
295 error mmmagic@0.4.1 install: `node-gyp rebuild`
295 error Exit status 1
296 error Failed at the mmmagic@0.4.1 install script 'node-gyp rebuild'.
296 error This is most likely a problem with the mmmagic package,
296 error not with npm itself.
296 error Tell the author that this fails on your system:
296 error     node-gyp rebuild
296 error You can get their info via:
296 error     npm owner ls mmmagic
296 error There is likely additional logging output above.
297 verbose exit [ 1, true ]

I have node v4.2.1 but somehow I'm still getting this error while npm install.

**Comment by mscdex** [comment]
@gokceyucel That log snippet shows nothing. The actual problem would come before that.

**Comment by gokceyucel** [comment]
@mscdex You are right, sorry about that. I guess the problem is something related with the c++ compiler in my situation. I'll report back soon.
