### ISSUE TITLE
Module version mismatch. Expected 46, got 14

### ISSUE THREAD

**Issue by mitselek** [mscdex/mmmagic#66]
Hi. Getting such error when trying mmmagic with electron along with reference to [ATOM_SHELL_ASAR.js:137](https://github.com/atom/electron/blob/e5e4749eb3c592667922f87c1105981db9dd84f7/atom/common/lib/asar.coffee#L244)

Similar issue was brought up here: https://github.com/Level/level/issues/28
and resolved here https://github.com/Level/electron-demo/issues/1 with commit https://github.com/Level/electron-demo/commit/d3d4736d4f826ca9ef8a20a4364e7d8aead17e94

```shell
$ npm -v
3.3.10
$ node -v
v0.12.0
$ electron -v
v0.34.1
$ npm ls mmmagic
└── mmmagic@0.4.1 
```

**Comment by mscdex** [comment]
The major version of node used to build the addon is a different major version of node you're using the addon with.

In this case, it looks like the addon was built against node v4+ but you're trying to use it with node v0.12. Try doing an `npm rebuild` to rebuild the addon against the current version of node.

**Comment by mitselek** [comment]
```shell
$ sudo npm rebuild
$ node -v
v0.12.0
$ sudo npm cache clean -f
$ sudo npm install -g n
$ sudo n stable
$ node -v
v5.0.0
```
When I run my project, I still run into same exact version mismatch error (Expected 46, got 14).

**Comment by mitselek** [comment]
Downloaded official v4.2.1 LTS from https://nodejs.org/en/, rebuilt mmmagic with `npm install --save mmmagic` and versions match now.

**Comment by venkat-imaginea** [comment]
Simply upgrade node and nvm to 5.6.0 and 3.6.0 respectively.
