### ISSUE TITLE
The system cannot find message text for message number 0x%1 in the message file for %2

### ISSUE THREAD

**Issue by mitselek** [mscdex/mmmagic#69]
Have you encountered such (windows 7) error message:
```error
Uncaught Error: The system cannot find message text for message number 0x%1 in the message file for %2.
C:\Users\michelek\Documents\GitHub\panustaja\node_modules\mmmagic\build\Release\magic.node
```
it gets fired in atom-electron's asar.js module on request.

**Comment by mscdex** [comment]
Never seen that before. Does running `npm test` within `node_modules\mmmagic` exit without errors?

**Comment by mitselek** [comment]
No errors there.

**Comment by mscdex** [comment]
If there's no errors there, then I'm not sure what to tell you. Maybe it's something related to atom-electron?

**Comment by mitselek** [comment]
Smells like that :)
