### ISSUE TITLE
Weird error when passing the string '6.1.13'

### ISSUE THREAD

**Issue by mercmobily** [mscdex/mmmagic#77]
The library returns with a "[Error: Offset out of range]" error when evaluating the string:

'6.1.13'

To try it:

    var mmm = require('mmmagic');
    var Magic = mmm.Magic;
    var magic = new Magic( mmm.MAGIC_MIME_TYPE );

    magic.detect( new Buffer('6.1.13'), function( err, magic ){
      console.log("ERROR:", err );
    })

This only seems to happen on my server (not on the local machine) where I have GCC (via devtoolset-3 on CentOS):

    gcc (GCC) 4.9.1 20140922 (Red Hat 4.9.1-10)
    Copyright (C) 2014 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

And node: v4.4.0

Interestingly, it only seems to be doing it when the LAST number is a double-digit one. So, 6.3.10 fails, but 6.3.9 or 6.3.2 work.

Any hints?

**Comment by mscdex** [comment]
There was a regression upstream that was fixed post-libmagic v5.26. I have merged the fix that was made upstream now, can you please test the master branch?

**Comment by mercmobily** [comment]
Hi,

Confirmed as fixed -- thank you!
Out of curiosity, can you tell by looking at the patch what *actually* caused the "Offset out of range" error?!?

If not all good -- but yes, please close.

Merc.

**Comment by mscdex** [comment]
Thanks for the confirmation.

I basically just looked upstream and saw some offset-related commits. There was one that was an off-by-one bug and another related to DER parsing. I'm guessing it was one of those commits.

I will publish a new version soon.
