### ISSUE TITLE
Can't run mmmagic on Windows with Electron

### ISSUE THREAD

**Issue by thanpolas** [mscdex/mmmagic#81]
Hello,

I'm in the process of creating the Windows version of our Electron app, we use mmmagic which I managed to build successfully on windows, [albeit with a few warnings](https://gist.github.com/thanpolas/0ae030d789a6e6c42cf502908bc192cc).

The problem is that when I launch the Electron app I get this error:

```
 Error: A dynamic link library (DLL) initialization routine failed.
\\?\E:\reveal-win\node_modules\mmmagic\build\Release\magic.node
    at Error (native)
    at process.module.(anonymous function) (ATOM_SHELL_ASAR.js:159:20)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:159:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:159:20)
...
```

As I've seen in a similar problem for another package sass/node-sass#1047 this is a problem of binary bindings to atom shell which Electron uses... Got any tips for me?

Windows 10
npm -v 3.3.12
node -v 5.5.1
Electron-prebuilt: 0.36.7
Setup the windows environment [following this checklist](https://github.com/thanpolas/Practice/blob/master/NPM-Install-on-windows.md).

**Comment by mscdex** [comment]
This module doesn't utilize pre-compiled binaries and/or does not link against libmagic dynamically, so I'm not sure what the problem is. I have no experience with Electron. `mmmagic` builds and works just fine on [Windows in a normal node environment](https://ci.appveyor.com/project/mscdex/mmmagic) though.

**Comment by matthew-b-payne** [comment]
try the npm install with the form of 

npm --msvs_version=2013 install
(worked with that flag on)
