### ISSUE TITLE
deprecation warnings when used with node v6.2.0

### ISSUE THREAD

**Issue by deep9** [mscdex/mmmagic#83]
When using the module with Node.js v6.2.0, a deprecation warning (along with stack traces) is displayed on every call.

Also this can be seen in websockets/bufferutil#41

**Comment by mscdex** [comment]
What version of `nan` installed for you?

**Comment by deep9** [comment]
There is nan@2.2.1 with bcrypt@0.8.6, nan@1.4.3 with ws@0.5.0 (Socket.io) and nan@0.3.2 with  ws@0.4.31 (Socket.io-client) installed.

**Comment by deep9** [comment]
By installing current `nan@2.3.3` and after that running `npm install` the deprecated warning is not shown anymore.

**Comment by mscdex** [comment]
Hrmm ok, typically the latest `nan` should be picked up during `npm install mmmagic` though.

**Comment by deep9** [comment]
Well I think that npm was happy with `bcrypt`s `nan@2.2.1`. If I install without `bcrypt`, then `mmmagic `will install `nan@2.3.3`

**Comment by mscdex** [comment]
Ah, I see.

**Comment by klimashkin** [comment]
This can be closed, bcrypt 0.8.7 uses new nan now
https://github.com/ncb000gt/node.bcrypt.js/commit/3769e70de894d4dad8b1facc75ba634b780c0a65

**Comment by mscdex** [comment]
@klimashkin Thanks for the update.
