### ISSUE TITLE
Incorrectly reports "ISO Media, MPEG v4 system, 3GPP" as "application/octet-stream"

### ISSUE THREAD

**Issue by michael-ts** [mscdex/mmmagic#84]
When I run the example on a 3GP file but omit `mmm.MAGIC_MIME_TYPE` from the constructor, it correctly returns `ISO Media, MPEG v4 system, 3GPP`.  But when I try to get the MIME type it returns `application/octet-stream` instead of the correct MIME type, which is `video/3gpp` which for comparison the `file` command returns.

**Comment by mscdex** [comment]
For issues regarding actual information returned by this addon, you should file an issue over on [`file`'s issue tracker](http://bugs.gw.com/my_view_page.php). Also, there seems to be an existing related issue [here](http://bugs.gw.com/view.php?id=444) that you may want to chime in on and provide a test file for the developer to test against.

**Comment by michael-ts** [comment]
This behavior diverges from that of the `file` command, which correctly reports the MIME type...

**Comment by mscdex** [comment]
This addon bundles up-to-date versions of libmagic, so it's entirely possible that there is a regression compared to an older system-wide copy of `file`.

**Comment by michael-ts** [comment]
Ah, so there is... the newer version of `file` indeed has the same problem.
