### ISSUE TITLE
Can't use custom magic.mgc files

### ISSUE THREAD

**Issue by michael-ts** [mscdex/mmmagic#85]
I created a modified magic.mgc file to add support for a file type (MOV identified by "pnot" at offset 4) which wasn't recognized by "mmmagic".  But when I pass the path to this file as the first argument to `new Magic()` it still doesn't recognize my file.

I replaced the standard system magic.mgc file in `/usr/share/file` and passed `false` as the argument to the constructor instead, and it still didn't recognize the new file type.  I confirmed that the `file` command now correctly identifies my file.

Finally, I replaced the magic.mgc file directly in the package (`node_modules/mmmagic/magic/magic.mgc`).   Now I get an exception:

> Error: could not load any valid magic files!

Since this file is recognized by the system `file` command it must be a valid file, right?  Is this file format not cross platform?   The first four bytes of the default and my magic.mgc are identical.   The default however is 4 times larger, although this could just be a more comprehensive set of magic numbers.

**Comment by michael-ts** [comment]
Ok, I'm not sure what I changed, but now I'm getting this error:

Error: File 5.26 supports only version 13 magic files. `./magic.mgc' is version 7

I'm not sure exactly how to get the correct version, as `file` on my system is apparently compiling to version 7.

**Comment by mscdex** [comment]
You'll have to compile `file` 5.26 and use that binary to build a custom .mgc since `file`'s .mgc binary format changes from time to time.

**Comment by michael-ts** [comment]
Ok, that worked.  It no longer gives an error.  I still don't think it's actually using the file though, because it doesn't recognize the new file format I just added.

**Comment by michael-ts** [comment]
Oh, never mind... different version of file appears to be using a different base directory to compile from.
