### ISSUE TITLE
magic.node: failed to map segment from shared object: Operation not permitted

### ISSUE THREAD

**Issue by marcelboettcher** [mscdex/mmmagic#87]
Hey, getting this error on Ubuntu 14.04 with node 4.3.0, 5.10.1 and 6.3.0.

`node_modules/mmmagic/build/Release/magic.node: failed to map segment from shared object: Operation not permitted`

Any idea? Have the same problem with https://github.com/xissy/node-boilerpipe

Thx, Marcel

**Comment by mscdex** [comment]
Google says it has something to do with `/tmp` or the path in the `TMP` environment variable being noexec. Did you check that?

**Comment by marcelboettcher** [comment]
thx, my /tmp folder is rwx for everyone. My TMP environment variable from the system is empty.

**Comment by mscdex** [comment]
I mean check if `/tmp` is mounted with the `noexec` option. Which path/filesystem are you installing mmmagic on? Perhaps the place where `magic.node` is located is on a mounted path with `noexec`?

Either way, you can check with `mount | grep noexec`.
