### ISSUE TITLE
Query: 32/64 bit support for Windows

### ISSUE THREAD

**Issue by aaronpcz** [mscdex/mmmagic#88]
Just a quick query.

Are both 32/64 bit versions of Windows support?

Cheers

**Comment by mscdex** [comment]
Yes, both 32-bit and 64-bit Windows should work.

**Comment by aaronpcz** [comment]
Great thanks,

I'm currently using nodejs and Azure so we are precompiling the dependency as only solution for working with this module on an Azure web app (app service) instance as they do not have the VS C++ build tools required.  Could be nice to document this particular requirement for Azure web apps as it may save some people time in the future.
