### ISSUE TITLE
npm install mmmagic fails on alpine linux

### ISSUE THREAD

**Issue by sam1111** [mscdex/mmmagic#89]
Hi,

While trying to do npm install mmmagic on alipne linux with nodejs version 6.3.0-r0 and g++ 6.1.1-r0 and make 4.2.1-r0.  it fails saying ../deps/libmagic/src/file.h:540:21: fatal error: xlocale.h: No such file or directory.
compilation terminated.

Any other dependency here that I am missing on alpine linux? and what are all supported os of mmmagic?

**Comment by mscdex** [comment]
I don't test with musl much in general, which is what Alpine Linux uses. musl does not currently support xlocale, but I will have a fix for that shortly.

**Comment by mscdex** [comment]
Ok, a557cc24b09bdb82dbff57f8408962be67d2a979 should fix this. Can you verify this with `npm install https://github.com/mscdex/mmmagic/tarball/master` ?

**Comment by sam1111** [comment]
yes. it does solve the problem. Can you publish these changes in a new version of mmmagic on npm?

**Comment by mscdex** [comment]
The build error is due to one Travis CI machine failing because of a network issue and can be disregarded.

Thank you for the confirmation.

**Comment by sam1111** [comment]
Are these changes already in mmmagic 0.4.4?

**Comment by mscdex** [comment]
No, I have to publish a new version. I want to include some other changes still, so I won't be publishing just yet.

**Comment by sam1111** [comment]
Okay. Could you please share when are you planning to publish this change?

**Comment by mscdex** [comment]
v0.4.5 is published.

**Comment by sam1111** [comment]
Awesome 👍  . Thanks :)
