### ISSUE TITLE
Getting errors while npm install mmmagic

### ISSUE THREAD

**Issue by Bramzor** [mscdex/mmmagic#93]
Getting a lot of errors while installing mmmagic.
This is the case on Mac OSX and on Ubuntu 16.04 LTS

  CC(target) Release/obj.target/libpcre/deps/libmagic/pcre/pcreposix.o
  AR(target) Release/obj.target/deps/libmagic/pcre/pcre.a
  COPY Release/pcre.a
  CXX(target) Release/obj.target/magic/src/magic.o
../src/magic.cc:12:5: error: ‘uv_work_t’ does not name a type
     uv_work_t request;
     ^
../src/magic.cc:32:33: error: expected class-name before ‘{’ token
 class Magic : public ObjectWrap {
                                 ^
../src/magic.cc:54:36: error: ‘Arguments’ does not name a type
     static Handle<Value> New(const Arguments& args) {
                                    ^
../src/magic.cc:102:43: error: ‘Arguments’ does not name a type
     static Handle<Value> DetectFile(const Arguments& args) {
                                           ^
../src/magic.cc:139:39: error: ‘Arguments’ does not name a type
     static Handle<Value> Detect(const Arguments& args) {
                                       ^
../src/magic.cc:184:28: error: ‘uv_work_t’ has not been declared
     static void DetectWork(uv_work_t\* req) {
                            ^
../src/magic.cc:222:29: error: ‘uv_work_t’ has not been declared
     static void DetectAfter(uv_work_t\* req) {
                             ^
../src/magic.cc:261:44: error: ‘Arguments’ does not name a type
     static Handle<Value> SetFallback(const Arguments& args) {
                                            ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../src/magic.cc:1:
/usr/include/nodejs/deps/v8/include/v8.h: In static member function ‘static v8::Handlev8::Value Magic::New(const int&)’:
/usr/include/nodejs/deps/v8/include/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}

Any ideas?

**Comment by mscdex** [comment]
You're installing an old version of `mmmagic`. Recent versions on npm have been converted to use `nan`.

**Comment by M1TKO** [comment]
Try to install it on NodeJs version 6.11.1 LTS :smile:
