### ISSUE TITLE
mmmagic fails to install on windows without python

### ISSUE THREAD

**Issue by josebrwn** [mscdex/mmmagic#96]
Perhaps these dependencies should be in the requirements section of the documentation?

> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> gyp ERR! stack     at failNoPython (C:\Users\Joe\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
> gyp ERR! stack     at C:\Users\Joe\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
> gyp ERR! System Windows_NT 10.0.10586
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Joe\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\temp\mysite\node_modules\mmmagic
> gyp ERR! node -v v6.9.1
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Joe\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "mmmagic" "--save"
> npm ERR! node v6.9.1
> npm ERR! npm  v3.10.5
> npm ERR! code ELIFECYCLE
> 
> npm ERR! mmmagic@0.4.5 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the mmmagic@0.4.5 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the mmmagic package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs mmmagic
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls mmmagic
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\temp\mysite\npm-debug.log
> 
> C:\temp\mysite>npm remove mmmagic

**Comment by mscdex** [comment]
Python and other implicit dependencies are noted in the [node-gyp documentation](https://github.com/nodejs/node-gyp/) which applies to *all* node addons.
